<a href="https://colab.research.google.com/github/hadiah115-tech/code-switching-codesaviours-si26-hadia/blob/main/SI26_Week6_hadia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd

print("Project 2 Started")

Project 2 Started

In [21]:
import pandas as pd

print("Code Saviours SI-26")
print("Project 2 - Code Switching Dataset")

Code Saviours SI-26
Project 2 - Code Switching Dataset

In [22]:
df = pd.read_csv("dataset.csv")

df.head()

                    sentence   word label
0  Aaj ka din bohot busy tha    Aaj   URD
1  Aaj ka din bohot busy tha     ka   URD
2  Aaj ka din bohot busy tha    din   URD
3  Aaj ka din bohot busy tha  bohot   URD
4  Aaj ka din bohot busy tha   busy   ENG

In [23]:
print("Total Word Entries:", len(df))

Total Word Entries: 1358

In [24]:
print("Total Sentences:", df["sentence"].nunique())

Total Sentences: 150

In [25]:
print("Label Distribution")
print(df["label"].value_counts())

Label Distribution
label
ENG    868
URD    490
Name: count, dtype: int64

In [26]:
df.sample(10)

                                               sentence       word label
215         Tumhara idea bohot brilliant tha I loved it          I   ENG
738   Bhai playlist change karo play some upbeat tracks       some   ENG
820       Mujhe shortcut pata hai we will reach quickly       will   ENG
256   Bahar mausam bohot awesome hai let us go for a...     mausam   URD
134         Suno message check karo I sent you the file        you   ENG
323        Mujhe naya phone lena hai suggestion do fast      Mujhe   URD
1093  Kal mera interview scheduled hai preparing ans...     answer   ENG
453   Mera subscription expire ho gaya hai need to r...     expire   ENG
592   Mera exam center bohot door tha reached just i...       door   URD
1130  Unka product design is modern customer loved i...  interface   ENG

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1358 entries, 0 to 1357
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sentence  1358 non-null   object
 1   word      1357 non-null   object
 2   label     1358 non-null   object
dtypes: object(3)
memory usage: 32.0+ KB

In [28]:
print("Dataset loaded successfully!")

Dataset loaded successfully!